common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: blog
  password: YVLUBjU7fp8qHL # from psql setup, see Postgresql

development:
  <<: *common
  database: blog_development

test:
  <<: *common
  database: blog_test

production:
  <<: *common
  database: blog_production