common: &common
  adapter: postgresql
  username: blog
  password: YVLUBjU7fp8qHL # from psql setup, see Postgresql

development:
  <<: *common
  database: blog_development

test:
  <<: *common
  database: blog_test

production:
  <<: *common
  database: blog_production